# Problema array. Dado uma posição no array, retornar os valores daquela posição até o última

In [1]:
def list_slice(l, index):
    return l[index:]  
    

In [2]:
lista = [2, 3, 4, 5, 6, 7]
list_slice(lista, 3)

[5, 6, 7]

# Problema Matriz

Dado uma matriz MxN de números inteiros, indique uma posição na matriz e leia desta posição em diante.

In [3]:
import numpy as np

# matrix with m rows and n columns
def create_matrix(m, n, min_, max_):
    return np.random.random_integers(min_, max_, (m, n))

In [4]:
matrix = create_matrix(3, 4, 1, 23)
matrix

<ipython-input-3-0784c1115c04>:5: DeprecationWarning: This function is deprecated. Please call randint(1, 23 + 1) instead
  return np.random.random_integers(min_, max_, (m, n))


array([[13,  6,  2, 11],
       [20, 20,  9,  2],
       [16, 17, 21,  5]])

In [5]:
matrix[0][0]

13

In [6]:
matrix[1][2]  # row, column

9

In [7]:
matrix.shape

(3, 4)

In [13]:
def slice_matrix(matrix, position):
    
    rows, columns = matrix.shape
    
    for r in range(position[0], rows):
        for c in range(position[1], columns):
            print(matrix[r][c])

In [14]:
matrix

array([[13,  6,  2, 11],
       [20, 20,  9,  2],
       [16, 17, 21,  5]])

In [15]:
p = (0, 1)
slice_matrix(matrix, p)

6
2
11
20
9
2
17
21
5


In [18]:
matrix

array([[13,  6,  2, 11],
       [20, 20,  9,  2],
       [16, 17, 21,  5]])

In [97]:
def slice_matrix_2(matrix, position, flag=1):
    
    rows, columns = matrix.shape
    
    if flag == 1:  # iterate over rows
        for col_temp in range(position[1], columns):
            print(matrix[position[0]][col_temp], end=' ')
        print("")
        for r in range(position[0]+1, rows):
            for c in range(columns):
                print(matrix[r][c], end=' ')
            print("")

    elif flag == 2: # iterate over columns        
        for row_temp in range(position[0], rows):
            print(matrix[row_temp][position[1]])        
        for c in range(position[1]+1, columns):
            for r in range(rows):
                print(matrix[r][c])

In [98]:
p = (0, 1)

slice_matrix_2(matrix, p)

6 2 11 
20 20 9 2 
16 17 21 5 


In [99]:
p = (1, 1)

slice_matrix_2(matrix, p, 2)

20
17
2
9
21
11
2
5


# Imprimir Triângulos

In [218]:
def print_triangles(x):
    
    """
    x: triangle height
    """
    
    k = x - 1  # number of spaces

    for i in range(x):
        for j in range(k):
            print(end = " ")
        k = k - 1
        
        for j in range(i+1):
            
            print("* ", end="")
        
        print("\r")

In [219]:
print_triangles(5)

    * 
   * * 
  * * * 
 * * * * 
* * * * * 


# Imprimir Losangos

In [277]:
def print_diamond(x):    
    for i in range(x):
        print(" " * (x - i), "*" * (i * 2 + 1))

    for i in range(x-2, -1, -1):
        print(" " * (x - i), "*" * (i * 2 + 1))    

In [278]:
print_diamond(5)

      *
     ***
    *****
   *******
  *********
   *******
    *****
     ***
      *
